### ISSUE TITLE
unable to export: PHP Fatal error:  Uncaught exception 'Alchemy\Zippy\Exception\RuntimeException'

### ISSUE THREAD

**Issue by cloudchou** [benbalter/wordpress-to-jekyll-exporter#86]
When I try to export in the command line,  I come across this problem:
PHP Fatal error:  Uncaught exception 'Alchemy\Zippy\Exception\RuntimeException' with message 'unable to add ./wp-content/uploads/2016/10/ to the zip file' in /home/cloud/www/wordpress/wp-content/plugins/wordpress-to-jekyll-exporter-2.0.1/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/ZipExtensionAdapter.php:324
Stack trace:
#0 /home/cloud/www/wordpress/wp-content/plugins/wordpress-to-jekyll-exporter-2.0.1/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/ZipExtensionAdapter.php(272): Alchemy\Zippy\Adapter\ZipExtensionAdapter->addEmptyDir(Object(ZipArchive), './wp-content/up...')
#1 /home/cloud/www/wordpress/wp-content/plugins/wordpress-to-jekyll-exporter-2.0.1/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/ZipExtensionAdapter.php(194): Alchemy\Zippy\Adapter\ZipExtensionAdapter->addEntries(Object(Alchemy\Zippy\Adapter\Resource\ZipArchiveResource), Array, true)
#2 /home/cloud/www/wordpress/wp-content/plugins/wordpress-to-jekyll-exporter-2.0.1/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/AbstractAdapter.php(56): Alchemy\Zippy\Adap in /home/cloud/www/wordpress/wp-content/plugins/wordpress-to-jekyll-exporter-2.0.1/vendor/alchemy/zippy/src/Alchemy/Zippy/Zippy.php on line 63

**Comment by cloudchou** [comment]
maybe the reason is that you forget to mkdir for emptydir in  /tmp/zip_xxx
